spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/music_streaming_service
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create